version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "actions/*"
  # Keep maven-dependencies up to date
  - package-ecosystem: "maven"
    directory: /
    schedule:
      interval: "daily"
    groups:
      maven-plugins:
        patterns:
          - "org.apache.maven.plugins:*"
          - "org.codehaus.mojo:*"
