version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Keep maven-dependencies up to date
  - package-ecosystem: "maven"
    directory: /
    schedule:
      interval: "daily"
