image: maven:3.3-jdk-8

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn -V -B -s .ci/settings.xml clean install -DskipITs
  branches:
    master:
      - step:
          caches:
            - maven
          script:
            - mvn -V -B -s .ci/settings.xml clean install -DskipITs
            - mvn -B -s .ci/settings.xml deploy -DskipTests -DskipITs
  tags:
    geocoding-*:
      - step:
          script:
            - mvn -V -B -s .ci/settings.xml clean install -DskipITs
            - mvn -B -s .ci/settings.xml deploy -DskipTests -DskipITs