name: Build & Test

on:
  push:
    branches-ignore:
      - "main"
      - "maintenance/v*"
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Java/Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Compile & Test
        run: ./mvnw -V -B --no-transfer-progress
          clean package verify
          -Dnominatim.email="${{ secrets.NOMINATIM_USER }}"
          -Dgoogle.apiKey="${{ secrets.GOOGLE_API_KEY }}"
          -Psonarcloud
          -Dsonar.projectKey=redlink-gmbh_redlink-geocoding
          -Dsonar.skip=${{ github.actor == 'dependabot[bot]' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: '**/TEST-*.xml'
